/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.clightning4j.litebtc;

import io.github.clightning4j.litebtc.exceptions.LiteBitcoinRPCException;
import io.github.clightning4j.litebtc.model.generic.Configuration;
import io.github.clightning4j.litebtc.model.generic.Parameters;

public class LiteBitcoinRPC {

    private Configuration configuration;

    public LiteBitcoinRPC(Configuration configuration) {
        this.configuration = configuration;
    }

    public LiteBitcoinRPC(String user, String pass) {
        this.configuration = new Configuration(user, pass);
    }

    public LiteBitcoinRPC(String cookiePath) {
        this.configuration = new Configuration(cookiePath);
    }

    public <T> T makeBitcoinRequest(Parameters parameters) throws LiteBitcoinRPCException {
        if (parameters == null) {
            throw new LiteBitcoinRPCException("Function argument null");
        }
        return null;
    }

    public <T> T makeBitcoinRequest(String parameter) throws LiteBitcoinRPCException {
        Parameters parameters = new Parameters();
        parameters.addParameter("name", null);
        return this.makeBitcoinRequest(parameters);
    }
}
